# Generated by Django 5.2.7 on 2026-03-05 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Technicien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('specialite', models.CharField(choices=[('electricien', 'Electricien'), ('plombier', 'Plombier'), ('ingenieur', 'Ingenieur en construction'), ('soudeur', 'Soudeur'), ('peintre', 'Peintre'), ('menuisier', 'Menuisier'), ('surveillance', 'Camera de surveillance')], max_length=30)),
                ('telephone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('localite', models.CharField(max_length=200)),
                ('disponibilite', models.CharField(choices=[('disponible', 'Disponible'), ('occupe', 'Occupe'), ('conge', 'En conge')], default='disponible', max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='techniciens/')),
                ('experience', models.IntegerField(default=0)),
                ('actif', models.BooleanField(default=True)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['specialite', 'nom'],
            },
        ),
    ]
