# Generated by Django 6.0.3 on 2026-03-11 11:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demandes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InstructionPaiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode_paiement', models.CharField(choices=[('carte', 'Carte Bancaire'), ('livraison', 'À la Livraison'), ('mobile', 'Mobile Money')], max_length=20, unique=True, verbose_name='Mode de paiement')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(verbose_name='Description générale')),
                ('etapes', models.JSONField(default=list, help_text='Liste des étapes sous forme de tableau JSON. Ex: ["Étape 1...", "Étape 2..."]', verbose_name='Étapes (liste)')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Instruction de paiement',
                'verbose_name_plural': 'Instructions de paiement',
                'db_table': 'instructions_paiement',
            },
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode_paiement', models.CharField(choices=[('carte', 'Carte Bancaire'), ('livraison', 'À la Livraison'), ('mobile', 'Mobile Money')], max_length=20, verbose_name='Mode de paiement')),
                ('fournisseur_mobile', models.CharField(blank=True, choices=[('lumicash', 'Lumicash'), ('ecocash', 'Ecocash')], max_length=20, null=True, verbose_name='Fournisseur mobile')),
                ('numero_mobile', models.CharField(blank=True, max_length=20, null=True, verbose_name='Numéro mobile')),
                ('derniers_chiffres_carte', models.CharField(blank=True, max_length=4, null=True, verbose_name='4 derniers chiffres carte')),
                ('nom_titulaire_carte', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nom du titulaire')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant (BIF)')),
                ('devise', models.CharField(default='BIF', max_length=5)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('valide', 'Validé'), ('rejete', 'Rejeté'), ('annule', 'Annulé')], default='en_attente', max_length=20, verbose_name='Statut')),
                ('note_admin', models.TextField(blank=True, null=True, verbose_name="Note de l'admin")),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paiements', to=settings.AUTH_USER_MODEL, verbose_name='Client')),
                ('commande', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='paiements', to='demandes.demande', verbose_name='Demande')),
                ('valide_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements_valides', to=settings.AUTH_USER_MODEL, verbose_name='Validé par')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'db_table': 'paiements',
                'ordering': ['-created_at'],
            },
        ),
    ]
