# Generated by Django 6.0.3 on 2026-03-11 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demandes', '0002_instructionpaiement_paiement'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='lien',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='paiement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='demandes.paiement'),
        ),
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(default='info', max_length=50),
        ),
        migrations.AlterField(
            model_name='notification',
            name='titre',
            field=models.CharField(default='Notification', max_length=255),
        ),
    ]
