# Generated by Django 6.0.3 on 2026-03-11 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demandes', '0003_notification_lien_notification_paiement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='bordereau_soumis',
            field=models.BooleanField(default=False, verbose_name='Bordereau soumis par le client'),
        ),
        migrations.AddField(
            model_name='paiement',
            name='date_soumission_bordereau',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de soumission du bordereau'),
        ),
        migrations.AddField(
            model_name='paiement',
            name='date_virement',
            field=models.DateField(blank=True, null=True, verbose_name='Date du virement'),
        ),
        migrations.AddField(
            model_name='paiement',
            name='nom_expediteur',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name="Nom de l'expéditeur"),
        ),
        migrations.AddField(
            model_name='paiement',
            name='numero_bordereau',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Numéro de bordereau'),
        ),
        migrations.AddField(
            model_name='paiement',
            name='photo_recu',
            field=models.ImageField(blank=True, null=True, upload_to='paiements/recus/', verbose_name='Photo du reçu'),
        ),
    ]
