# Generated by Django 6.0.3 on 2026-03-18 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demandes', '0004_paiement_bordereau_soumis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='acces_dashboard_vip',
            field=models.BooleanField(default=False, verbose_name='Accès dashboard VIP'),
        ),
        migrations.AlterField(
            model_name='instructionpaiement',
            name='etapes',
            field=models.JSONField(default=list, help_text='Liste des étapes sous forme de tableau JSON.', verbose_name='Étapes (liste)'),
        ),
    ]
